--run file with psql postgres -f ./db/seedTopics.sql
\c blueocean

insert into topics(topic_name,topic_imageUrl,website_url,topic_description) values ('Children''s and Family Services','https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/children_family.gif?utm_source=DataAPI&utm_content=9af5afa3','https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=17&utm_source=DataAPI&utm_content=9af5afa3','These organizations provide family services, family care and adoption services to families across the world.');
insert into topics(topic_name,topic_imageUrl,website_url,topic_description) values ('Homeless Services','https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/homeless.jpg?utm_source=DataAPI&utm_content=9af5afa3','https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=28&utm_source=DataAPI&utm_content=9af5afa3','These organizations are focused on providing a large array of services and shelter to the homeless.');
insert into topics(topic_name,topic_imageUrl,website_url,topic_description) values ('Youth Development, Shelter, and Crisis Services','https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/youth_development.gif?utm_source=DataAPI&utm_content=9af5afa3','https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=16&utm_source=DataAPI&utm_content=9af5afa3','These organizations provide developmental, shelter and crisis services to youth whore are in need.');
insert into topics(topic_name,topic_imageUrl,website_url,topic_description) values ('Multipurpose Human Service Organizations','https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/multipurpose.gif?utm_source=DataAPI&utm_content=9af5afa3','https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=15&utm_source=DataAPI&utm_content=9af5afa3','These organizations provide a wide variety of basic humanitarian services, such as food, shelter, showers, and more.');
insert into topics(topic_name,topic_imageUrl,website_url,topic_description) values ('Food Banks, Food Pantries, and Food Distribution','https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/food_banks.gif?utm_source=DataAPI&utm_content=9af5afa3','https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=18&utm_source=DataAPI&utm_content=9af5afa3','These organizations have a primary focus on providing food to those in need by food banks, food pantries, and other food distribution methods.');
insert into topics(topic_name,topic_imageUrl,website_url,topic_description) values ('Social Services','https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/social_services.gif?utm_source=DataAPI&utm_content=9af5afa3','https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=6&cuid=29&utm_source=DataAPI&utm_content=9af5afa3','These organizations are focused on providing a wide variety of social services to low income communities, veterans, and more.');
insert into topics(topic_name,topic_imageUrl,website_url,topic_description) values ('Scholarship and Financial Support','https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/scholarships.gif?utm_source=DataAPI&utm_content=9af5afa3','https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=3&cuid=37&utm_source=DataAPI&utm_content=9af5afa3','These organizations raise funds to give out grants, scholarships, and financial support to those who are in need.');
-- insert into topics(topic_name,topic_imageUrl,website_url,topic_description) values ('Private Liberal Arts Colleges','https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/private_colleges.jpg?utm_source=DataAPI&utm_content=9af5afa3','https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=3&cuid=33&utm_source=DataAPI&utm_content=9af5afa3'); Doesn't return anything on Charity Navigator site.
insert into topics(topic_name,topic_imageUrl,website_url,topic_description) values ('Youth Education Programs and Services','https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/youth_education.gif?utm_source=DataAPI&utm_content=9af5afa3','https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=3&cuid=40&utm_source=DataAPI&utm_content=9af5afa3','These organizations have a focus on providing better education opportunities to youth who may not have ideal educational opportunities.');
insert into topics(topic_name,topic_imageUrl,website_url,topic_description) values ('Education Policy and Reform','https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/education_policy.gif?utm_source=DataAPI&utm_content=9af5afa3','https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=3&cuid=41&utm_source=DataAPI&utm_content=9af5afa3','These organizations are focused on creating new public education policies and education policy reformations.');
-- insert into topics(topic_name,topic_imageUrl,website_url,topic_description) values ('Other Education Programs and Services','https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/other_education.gif?utm_source=DataAPI&utm_content=9af5afa3','https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=3&cuid=7&utm_source=DataAPI&utm_content=9af5afa3'); Doesn't return anything on Charity Navigator site.
-- insert into topics(topic_name,topic_imageUrl,website_url,topic_description) values ('Private Elementary & Secondary Schools','https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/private_schools.gif?utm_source=DataAPI&utm_content=9af5afa3','https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=3&cuid=8&utm_source=DataAPI&utm_content=9af5afa3'); Doesn't return anything on Charity Navigator site.
-- insert into topics(topic_name,topic_imageUrl,website_url,topic_description) values ('Universities, Graduate Schools, and Technological Institutes','https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/universities.gif?utm_source=DataAPI&utm_content=9af5afa3','https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=3&cuid=9&utm_source=DataAPI&utm_content=9af5afa3'); Doesn't return anything on charity navigator site.
insert into topics(topic_name,topic_imageUrl,website_url,topic_description) values ('Adult Education Programs and Services','https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/adult_education.gif?utm_source=DataAPI&utm_content=9af5afa3','https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=3&cuid=39&utm_source=DataAPI&utm_content=9af5afa3','These organizations are focused on providing education opportunities to adults who may not have had good opportunities earlier in life.');
insert into topics(topic_name,topic_imageUrl,website_url,topic_description) values ('Early Childhood Programs and Services','https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/early_childhood.gif?utm_source=DataAPI&utm_content=9af5afa3','https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=3&cuid=36&utm_source=DataAPI&utm_content=9af5afa3','These organizations are focused on providing early education opportunities, books, and tutoring to young children.');
insert into topics(topic_name,topic_imageUrl,website_url,topic_description) values ('Special Education','https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/special_education.gif?utm_source=DataAPI&utm_content=9af5afa3','https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=3&cuid=38&utm_source=DataAPI&utm_content=9af5afa3','These organizations are focused on providing special education to those with special needs all across the globe.');
insert into topics(topic_name,topic_imageUrl,website_url,topic_description) values ('International Peace, Security, and Affairs','https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/international_peace.gif?utm_source=DataAPI&utm_content=9af5afa3','https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=7&cuid=19&utm_source=DataAPI&utm_content=9af5afa3','These organizations are focused on reducing violence, and improving peace, prosperity and security.');
insert into topics(topic_name,topic_imageUrl,website_url,topic_description) values ('Development and Relief Services','https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/development_relief.gif?utm_source=DataAPI&utm_content=9af5afa3','https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=7&cuid=20&utm_source=DataAPI&utm_content=9af5afa3','These organizations have a primary focus on providing infrastructure, health, and education improvements in developing countries.');
insert into topics(topic_name,topic_imageUrl,website_url,topic_description) values ('Humanitarian Relief Supplies','https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/humanitarian_relief.jpg?utm_source=DataAPI&utm_content=9af5afa3','https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=7&cuid=30&utm_source=DataAPI&utm_content=9af5afa3','These organizations have a focus on providing humanitarian relief, such as food and medical supplies, to those in need worldwide.');
-- insert into topics(topic_name,topic_imageUrl,website_url,topic_description) values ('Foreign Charity Support Organizations','https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/single_country.jpg?utm_source=DataAPI&utm_content=9af5afa3','https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=7&cuid=31&utm_source=DataAPI&utm_content=9af5afa3'); Doesn't return anything on charity navigator site.
insert into topics(topic_name,topic_imageUrl,website_url,topic_description) values ('Advocacy and Education','https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/advocacy.gif?utm_source=DataAPI&utm_content=9af5afa3','https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=8&cuid=21&utm_source=DataAPI&utm_content=9af5afa3','These charities are for advocation of education, as well as advocating for maintaining civil rights afforded by the Constitution.');
insert into topics(topic_name,topic_imageUrl,website_url,topic_description) values ('Religious Media and Broadcasting','https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/religious_media.gif?utm_source=DataAPI&utm_content=9af5afa3','https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=9&cuid=25&utm_source=DataAPI&utm_content=9af5afa3','Through the use of channels, such as radio and television, these organizations are spreading the words and messages of their doctrines.');
insert into topics(topic_name,topic_imageUrl,website_url,topic_description) values ('Religious Activities','https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/religious_activities.gif?utm_source=DataAPI&utm_content=9af5afa3','https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=9&cuid=26&utm_source=DataAPI&utm_content=9af5afa3','These religious organizations use their foundation for various charitable activities, such as providing food, grants, and shelter for those in need.');
insert into topics(topic_name,topic_imageUrl,website_url,topic_description) values ('Wildlife Conservation','https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/wildlife_conservation.gif?utm_source=DataAPI&utm_content=9af5afa3','https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=1&cuid=1&utm_source=DataAPI&utm_content=9af5afa3','These organizations advocate for and actively participate in wildlife conservation efforts all around the world.');
insert into topics(topic_name,topic_imageUrl,website_url,topic_description) values ('Animal Rights, Welfare, and Services','https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/animal_rights.gif?utm_source=DataAPI&utm_content=9af5afa3','https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=1&cuid=2&utm_source=DataAPI&utm_content=9af5afa3','The organizations advocate for animal rights, and welfare, in addition to providing service animals for those in need.');
insert into topics(topic_name,topic_imageUrl,website_url,topic_description) values ('Zoos and Aquariums','https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/zoos_aquariums.jpg?utm_source=DataAPI&utm_content=9af5afa3','https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=1&cuid=32&utm_source=DataAPI&utm_content=9af5afa3','These organizations provide wildlife conservation efforts, sanctuaries for animals, as well as educational opportunities.');
insert into topics(topic_name,topic_imageUrl,website_url,topic_description) values ('Libraries, Historical Societies and Landmark Preservation','https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/libraries.gif?utm_source=DataAPI&utm_content=9af5afa3','https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=2&cuid=6&utm_source=DataAPI&utm_content=9af5afa3','These organizations are focused on the preservation of libraries, historical knowledge, as well as maintaining and preserving historical monuments.');
insert into topics(topic_name,topic_imageUrl,website_url,topic_description) values ('Museums','https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/museums.gif?utm_source=DataAPI&utm_content=9af5afa3','https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=2&cuid=3&utm_source=DataAPI&utm_content=9af5afa3','These museums vary greatly in size, and type, but all are focused on maintaining and preserving educational opportunities across a wide array of subjects.');
insert into topics(topic_name,topic_imageUrl,website_url,topic_description) values ('Performing Arts','https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/performing_arts.gif?utm_source=DataAPI&utm_content=9af5afa3','https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=2&cuid=4&utm_source=DataAPI&utm_content=9af5afa3','These organizations are focused primarily on maintaining opportunities to experience performing arts; as well some providing opportunities to join in on the arts as well.');
insert into topics(topic_name,topic_imageUrl,website_url,topic_description) values ('Public Broadcasting and Media','https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/public_radio.gif?utm_source=DataAPI&utm_content=9af5afa3','https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=2&cuid=5&utm_source=DataAPI&utm_content=9af5afa3','These organizations are focused on providing free or cheap, publicly accessible media and broadcasting services.');
insert into topics(topic_name,topic_imageUrl,website_url,topic_description) values ('Botanical Gardens, Parks, and Nature Centers','https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/botanical_gardens.gif?utm_source=DataAPI&utm_content=9af5afa3','https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=4&cuid=10&utm_source=DataAPI&utm_content=9af5afa3','These organizations are focused on maintaining natural spaces and they need your help. Donate so that caretakers can keep these spaces safe and accessible for tourists while protecting native plants and wildlife. Volunteer so that visitors can enjoy your local gardens, parks, and nature centers at their best.');
insert into topics(topic_name,topic_imageUrl,website_url,topic_description) values ('Environmental Protection and Conservation','https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/environmental_protection.gif?utm_source=DataAPI&utm_content=9af5afa3','https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=4&cuid=11&utm_source=DataAPI&utm_content=9af5afa3','These organizations are focused on environmental protection and conservation for wildlife. Land and ocean plants and animals need your help to survive a swarm of challenges. Donate and volunteer so we can gift future generations the beauty that is ours to protect.');
insert into topics(topic_name,topic_imageUrl,website_url,topic_description) values ('Patient and Family Support','https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/patient_and_family_support.gif?utm_source=DataAPI&utm_content=9af5afa3','https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=5&cuid=34&utm_source=DataAPI&utm_content=9af5afa3','These organizations are focused on supporting the families and patients of life threatening illnesses, such as breast and prostate cancer. No family should have to face these challenges alone; volunteer in your community to make a difference in your neighbors lives in their time of need. Donate to ease the financial burden placed on families in crisis.');
insert into topics(topic_name,topic_imageUrl,website_url,topic_description) values ('Diseases, Disorders, and Disciplines','https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/diseases.gif?utm_source=DataAPI&utm_content=9af5afa3','https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=5&cuid=13&utm_source=DataAPI&utm_content=9af5afa3','These organizations are focused on finding cures and treatments for life threatening illness, such as cystic fibrosis, and cancer. As long as there are obstacles to our well being, your donations can fund the effort of those that dedicate their lives to helping patients overcome those obstacles. Volunteer in your community to aid these brave health care professionals in their quest to save lives.');
insert into topics(topic_name,topic_imageUrl,website_url,topic_description) values ('Treatment and Prevention Services','https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/treatment.gif?utm_source=DataAPI&utm_content=9af5afa3','https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=5&cuid=12&utm_source=DataAPI&utm_content=9af5afa3','These organizations are focused on providing treatments and helping prevent ailments of all types. Volunteer at local clinics and treatment facilities to educate neighbors and help those in need. Donate to bring cutting edge treatments and preventative medicine to those that need it the most.');
insert into topics(topic_name,topic_imageUrl,website_url,topic_description) values ('Medical Research','https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/medical_research.gif?utm_source=DataAPI&utm_content=9af5afa3','https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=5&cuid=14&utm_source=DataAPI&utm_content=9af5afa3','These organizations are focused on providing medical research, such as treatments, cures, and improvement of medical procedures and surgeries. Where people are hurting, your donations can bring them closer to relief. Volunteer at local hospitals and treatment centers to assist patients and health care professionals find wellness.');
insert into topics(topic_name,topic_imageUrl,website_url,topic_description) values ('Community Foundations','https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/community_foundations.gif?utm_source=DataAPI&utm_content=9af5afa3','https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=10&cuid=22&utm_source=DataAPI&utm_content=9af5afa3','These organizations are focused on providing funding and work for community improvement and maintenance all across the globe. Donations transform ideas and community spaces into thriving beneficial projects all over the world. Volunteers bring ideas to life; see how you can impact the community in your area.');
insert into topics(topic_name,topic_imageUrl,website_url,topic_description) values ('Housing and Neighborhood Development','https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/housing.gif?utm_source=DataAPI&utm_content=9af5afa3','https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=10&cuid=27&utm_source=DataAPI&utm_content=9af5afa3','These organizations are focused on providing housing and neighborhood development for low income communities. Volunteer to build low income housing or aid development organizers in other ways that impact your neighbors in need. Donate to keep those in need in a safe home while they work to better themselves and their community.');
insert into topics(topic_name,topic_imageUrl,website_url,topic_description) values ('United Ways','https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/United_Way.gif?utm_source=DataAPI&utm_content=9af5afa3','https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=10&cuid=42&utm_source=DataAPI&utm_content=9af5afa3','These charities are all part of the United Ways Worldwide Network, focused on improving education, financial stability, and health. Your donations directly affect thousands of people across the globe. There are lots of opportunities to get involved; sign up to volunteer at a local branch.');
insert into topics(topic_name,topic_imageUrl,website_url,topic_description) values ('Jewish Federations','https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/Jewish_Federation.jpg?utm_source=DataAPI&utm_content=9af5afa3','https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=10&cuid=43&utm_source=DataAPI&utm_content=9af5afa3','These organizations are all under the Jewish Federation, which focuses on providing humanitarian efforts across most of North America. When people are in need, your donations enable this charity to help them. Volunteering opportunities arise often so visit the link for more information about how you can get involved in your neighborhood.');
insert into topics(topic_name,topic_imageUrl,website_url,topic_description) values ('Non-Medical Science & Technology Research','https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/nonmedical.jpg?utm_source=DataAPI&utm_content=9af5afa3','https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=11&cuid=35&utm_source=DataAPI&utm_content=9af5afa3','These organizations are focused on researching scientific and technological breakthroughs not related to medical research. Your donations contribute to the greatest discoveries we haven’t discovered yet!’ Volunteers are also appreciated as every genius needs a few extra hands in the lab.');
insert into topics(topic_name,topic_imageUrl,website_url,topic_description) values ('Social and Public Policy Research','https://d20umu42aunjpx.cloudfront.net/_gfx_/causes/small/research_public_policy.gif?utm_source=DataAPI&utm_content=9af5afa3','https://www.charitynavigator.org/index.cfm?bay=search.results&cgid=11&cuid=24&utm_source=DataAPI&utm_content=9af5afa3','These organizations are focused on providing research for a variety of social, and public policy makers. When the lives of citizens are directly affected by the decisions of the few, it’s important that the decision makers have the best information to make the best decisions. Volunteer and donate to ensure that the people in charge get it right.');